FROM python:3.11-slim

WORKDIR /tests

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    gnupg \
    chromium \
    chromium-driver \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir selenium==4.18.1 pytest

COPY tests/ .

CMD ["python", "-m", "pytest", "test_selenium.py", "-v"]
